#!/bin/bash
# install-dev.sh — deploy dev/ into the sandbox user's home. Run as ADMIN_USER (no root needed:
# ADMIN_USER may act as SANDBOX_USER without a password, see host/etc/sudoers.d/).
#
#   ./install-dev.sh                 show diffs, install changed files, rebuild the image if its inputs changed
#   ./install-dev.sh --check         show diffs only; exit 1 if the live files differ from the rendered repo
#   ./install-dev.sh --render <dir>  write the rendered files to <dir> and exit (no access to the live system)
#
# Files are rendered from the repo + devbox.conf + local/ first (see lib/common.sh), then compared with
# what is live. If something was changed in place (e.g. Claude Code rewriting its settings.json after
# /plugin), --check shows the diff; port it into the repo or local/, then re-run.
set -euo pipefail
REPO=$(cd "$(dirname "$0")" && pwd)
. "$REPO/lib/common.sh"
MODE="${1:---install}"
case "$MODE" in
  --install|--check) ;;
  --render) [ -n "${2:-}" ] || die "--render needs a directory" ;;
  *) sed -n '2,12p' "$0"; exit 2 ;;
esac
load_conf

# --- render into a staging dir: <stage>/<live path relative to the sandbox user's home>
STAGE=$(mktemp -d); trap 'rm -rf "$STAGE"' EXIT
chmod 755 "$STAGE"
render "$REPO/dev/bin/claude-dev"           "$STAGE/.local/bin/claude-dev"
render "$REPO/dev/gitconfig"                "$STAGE/.gitconfig"
for f in Containerfile entrypoint.sh init-firewall.sh bb; do
  render "$REPO/dev/sandbox/$f" "$STAGE/sandbox/$f"
done
{ echo "# EXTRA_DOMAINS from devbox.conf (generated by install-dev.sh)"
  for d in ${EXTRA_DOMAINS:-}; do echo "$d"; done; } > "$STAGE/sandbox/extra-domains"
mkdir -p "$STAGE/sandbox/claude-home"
merge_json "$REPO/dev/sandbox/claude-home/settings.json" "$REPO/local/claude-settings.json" \
  "$STAGE/sandbox/claude-home/settings.json"
{ cat "$REPO/dev/sandbox/claude-home/CLAUDE.md"
  [ -f "$REPO/local/CLAUDE.md" ] && { echo; cat "$REPO/local/CLAUDE.md"; } || true
} > "$STAGE/sandbox/claude-home/CLAUDE.md"

# staged path | mode
FILES=(
  ".local/bin/claude-dev|755"
  ".gitconfig|644"
  "sandbox/Containerfile|644"
  "sandbox/entrypoint.sh|755"
  "sandbox/init-firewall.sh|755"
  "sandbox/bb|755"
  "sandbox/extra-domains|644"
  "sandbox/claude-home/settings.json|644"
  "sandbox/claude-home/CLAUDE.md|644"
)
# changes to these need `claude-dev build`
IMAGE_INPUTS=" sandbox/Containerfile sandbox/entrypoint.sh sandbox/init-firewall.sh sandbox/bb sandbox/extra-domains "
# persistent dirs mounted into the container (see dev/bin/claude-dev)
DIRS=(claude-home history gh-config cache uv-share go bb-credentials)

if [ "$MODE" = --render ]; then
  mkdir -p "$2"; cp -a "$STAGE/." "$2/"; echo "rendered into $2"; exit 0
fi

# --- compare with / install into the live home
# ADMIN_USER's home is usually closed to SANDBOX_USER, so always run as it from / and move content through pipes
asdev() { (cd / && sudo -n -u "$SANDBOX_USER" -H "$@"); }
asdev true 2>/dev/null || die "cannot run commands as $SANDBOX_USER via 'sudo -n' — run install-host.sh first?"
DH=$(getent passwd "$SANDBOX_USER" | cut -d: -f6)
live_cat() { asdev cat "$1" 2>/dev/null || true; }
live_mode() { asdev stat -c %a "$1" 2>/dev/null || echo missing; }

drift=0 rebuild=0
for entry in "${FILES[@]}"; do
  IFS='|' read -r rel mode <<<"$entry"
  live="$DH/$rel"
  content_same=1; diff -q <(live_cat "$live") "$STAGE/$rel" >/dev/null || content_same=0
  lmode=$(live_mode "$live")
  [ "$content_same" = 1 ] && [ "$lmode" = "$mode" ] && continue
  drift=1
  echo "=== $live"
  [ "$content_same" = 1 ] || diff -u --label live --label repo <(live_cat "$live") "$STAGE/$rel" || true
  [ "$lmode" = "$mode" ] || echo "mode: live $lmode, repo $mode"
  [ "$MODE" = --check ] && continue
  asdev bash -c 'set -e; mkdir -p "$(dirname "$1")"; cat > "$1.new"; chmod "$2" "$1.new"; mv "$1.new" "$1"' \
    _ "$live" "$mode" < "$STAGE/$rel"
  echo "installed $live"
  [[ "$IMAGE_INPUTS" == *" $rel "* ]] && rebuild=1
done

# persistent dirs + empty Bitbucket credentials file (tokens are added by hand, never committed)
for d in "${DIRS[@]}"; do
  if ! asdev test -d "$DH/sandbox/$d"; then
    drift=1; echo "missing dir: $DH/sandbox/$d"
    [ "$MODE" = --check ] || asdev mkdir -p "$DH/sandbox/$d"
  fi
done
if [ "$MODE" = --install ]; then
  asdev chmod 700 "$DH/sandbox/bb-credentials"
  asdev bash -c 'f=$1; [ -e "$f" ] || { touch "$f"; chmod 600 "$f"; }' _ "$DH/sandbox/bb-credentials/credentials"
fi

if [ "$MODE" = --check ]; then
  [ "$drift" = 0 ] && echo "dev: live matches repo" || { echo "dev: DRIFT (see above)"; exit 1; }
  exit 0
fi

if [ "$rebuild" = 1 ]; then
  echo "image inputs changed — rebuilding"
  asdev "$DH/.local/bin/claude-dev" build
fi
[ "$drift" = 0 ] && echo "dev: nothing to do" || echo "dev: done (running sandboxes pick up changes on restart: claude-dev down/up)"
